import { chromium } from 'playwright';
const base='http://localhost:3376';
const cap='/tmp/claude-0/-home-user-Vhzin121212/05d4ab06-464b-53f0-8a5e-ee64dd5a72ec/scratchpad';
const nav=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const p=await (await nav.newContext({viewport:{width:1440,height:1000},colorScheme:'dark'})).newPage();
const erros=[]; p.on('pageerror',e=>erros.push(e.message));
await p.goto(base); await p.waitForTimeout(1500);
await p.fill('input[name=email]','lucas0@email.com'); await p.fill('input[name=senha]','aluno123');
await p.click('.painel-acesso button[type=submit]'); await p.waitForSelector('.lateral'); await p.waitForTimeout(1500);
await p.goto(`${base}/#/checkin`); await p.waitForTimeout(1800);
await p.screenshot({path:`${cap}/F1-checkin-aluno.png`, fullPage:true});
console.log('aluno · aulas hoje:', await p.locator('.checkin-agora').count(), '| botão:', await p.locator('.botao-checkin').first().textContent());
await p.goto(`${base}/#/loja`); await p.waitForTimeout(1600);
await p.screenshot({path:`${cap}/F2-loja-aluno.png`, fullPage:true});
await p.setViewportSize({width:390,height:844}); await p.goto(`${base}/#/checkin`); await p.waitForTimeout(1500);
await p.screenshot({path:`${cap}/F3-mobile-checkin.png`});
await nav.close(); console.log('erros:', erros.length);
