import { chromium } from 'playwright';
const base='http://localhost:3376';
const cap='/tmp/claude-0/-home-user-Vhzin121212/05d4ab06-464b-53f0-8a5e-ee64dd5a72ec/scratchpad';
const nav=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const p=await (await nav.newContext({viewport:{width:1440,height:1000}, colorScheme:'dark'})).newPage();
await p.goto(base); await p.waitForTimeout(2200);
await p.screenshot({path:`${cap}/E1-site-topo.png`, clip:{x:0,y:0,width:1440,height:1000}});
await p.evaluate(()=>document.getElementById('planos')?.scrollIntoView());
await p.waitForTimeout(900);
await p.screenshot({path:`${cap}/E2-planos.png`, clip:{x:0,y:0,width:1440,height:1000}});
await p.evaluate(()=>document.getElementById('loja')?.scrollIntoView());
await p.waitForTimeout(900);
await p.screenshot({path:`${cap}/E3-loja.png`, clip:{x:0,y:0,width:1440,height:1000}});
await p.evaluate(()=>window.scrollTo(0,0)); await p.waitForTimeout(500);
await p.fill('input[name=email]','dono@atak.com'); await p.fill('input[name=senha]','admin123');
await p.click('.painel-acesso button[type=submit]'); await p.waitForSelector('.lateral'); await p.waitForTimeout(2000);
await p.screenshot({path:`${cap}/E4-painel.png`, fullPage:true});
await p.goto(`${base}/#/checkin`); await p.waitForTimeout(1800);
await p.screenshot({path:`${cap}/E5-checkins.png`, fullPage:true});
await p.goto(`${base}/#/loja`); await p.waitForTimeout(1800);
await p.screenshot({path:`${cap}/E6-loja-gestao.png`, fullPage:true});
await nav.close();
console.log('capturado');
